name: Release

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write

        env:
            VERSION: ${{ github.ref_name }}

        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
              with:
                  persist-credentials: false

            - name: Install uv
              uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7

            - name: Build release distributions
              run: uv build

            - name: Create GitHub Release
              uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
              with:
                  tag_name: ${{ env.VERSION }}
                  files: dist/*
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish release distributions to PyPI
              uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # v1.9.0
              with:
                  packages-dir: dist/
